<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\ResultIterator;

use App\Domain\ResultIterator\Generated\AbstractCompanyResultIterator;

/**
 * The CompanyResultIterator class will iterate over results of Company class.
 */
class CompanyResultIterator extends AbstractCompanyResultIterator
{
}
