<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\ResultIterator;

use App\Domain\ResultIterator\Generated\AbstractOrderResultIterator;

/**
 * The OrderResultIterator class will iterate over results of Order class.
 */
class OrderResultIterator extends AbstractOrderResultIterator
{
}
