<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Infrastructure\Dao;

use App\Infrastructure\Dao\Generated\BaseProductDao;

/**
 * The ProductDao class will maintain the persistence of Product class into the products table.
 */
class ProductDao extends BaseProductDao
{
}
