<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Infrastructure\Dao;

use App\Domain\Model\ResetPasswordToken;
use App\Domain\Repository\ResetPasswordTokenRepository;
use App\Domain\Throwable\NotFound\ResetPasswordTokenNotFoundById;
use App\Infrastructure\Dao\Generated\BaseResetPasswordTokenDao;

/**
 * The ResetPasswordTokenDao class will maintain the persistence of ResetPasswordToken class into the reset_password_tokens table.
 */
class ResetPasswordTokenDao extends BaseResetPasswordTokenDao implements ResetPasswordTokenRepository
{
    /**
     * @throws ResetPasswordTokenNotFoundById
     */
    public function mustFindOneById(string $id): ResetPasswordToken
    {
        $resetPasswordToken = $this->findOne(['id' => $id]);

        if ($resetPasswordToken !== null) {
            return $resetPasswordToken;
        }

        throw new ResetPasswordTokenNotFoundById($id);
    }
}
