<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Infrastructure\Dao;

use App\Infrastructure\Dao\Generated\BaseRightDao;

/**
 * The RightDao class will maintain the persistence of Right class into the rights table.
 */
class RightDao extends BaseRightDao
{
}
