<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Infrastructure\Dao;

use App\Domain\Model\Role;
use App\Domain\Repository\RoleRepository;
use App\Domain\Throwable\NotFound\RoleNotFound;
use App\Infrastructure\Dao\Generated\BaseRoleDao;

/**
 * The RoleDao class will maintain the persistence of Role class into the roles table.
 */
class RoleDao extends BaseRoleDao implements RoleRepository
{
    /**
     * @throws RoleNotFound
     */
    public function mustFindOneById(string $id) : Role
    {
        $role = $this->findOne([ 'id' => $id ]);

        if ($role !== null) {
            return $role;
        }

        throw new RoleNotFound($id);
    }
}
