<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Infrastructure\Dao;

use App\Domain\Model\User;
use App\Domain\Repository\UserRepository;
use App\Domain\Throwable\Exist\UserWithEmailExist;
use App\Infrastructure\Dao\Generated\BaseUserDao;

/**
 * The UserDao class will maintain the persistence of User class into the users table.
 */
class UserDao extends BaseUserDao implements UserRepository
{
    public function create(User $user) : void
    {
        $this->save($user);
    }

    public function update(User $user) : void
    {
        $this->save($user);
    }

    /**
     * @throws UserWithEmailExist
     */
    public function mustNotFindOneWithEmail(string $email) : void
    {
        $user = $this->findOneByEmail($email);

        if ($user === null) {
            return;
        }

        throw new UserWithEmailExist($email);
    }
}
