<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\BaseCompany;
use Symfony\Component\Validator\Constraints as Assert;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Company class maps the 'companies' table in database.
 *
 * @Type
 */
class Company extends BaseCompany
{
    /**
     * @Assert\NotBlank
     * @Assert\Length(max = 255)
     */
    public function getName() : string
    {
        return parent::getName();
    }

    /**
     * @Assert\NotBlank(allowNull = true)
     * @Assert\Length(max = 255)
     * @@Assert\Url
     */
    public function getWebsite() : ?string
    {
        return parent::getWebsite();
    }

    /**
     * @Assert\NotBlank(allowNull = true)
     * @Assert\Length(max = 255)
     */
    public function getLogoFilename() : ?string
    {
        return parent::getLogoFilename();
    }
}
