<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\BaseCompany;
use Symfony\Component\Validator\Constraints as Assert;
use TheCodingMachine\GraphQLite\Annotations\Field;
use TheCodingMachine\GraphQLite\Annotations\Security;
use TheCodingMachine\GraphQLite\Annotations\Type;

use function array_merge;

/**
 * The Company class maps the 'companies' table in database.
 *
 * @Type
 */
class Company extends BaseCompany
{
    /**
     * @Assert\NotBlank
     * @Assert\Length(max = 255)
     * @Field
     */
    public function getName(): string
    {
        return parent::getName();
    }

    /**
     * @Assert\NotBlank(allowNull = true)
     * @Assert\Length(max = 255)
     * @Assert\Url
     * @Field
     */
    public function getWebsite(): ?string
    {
        return parent::getWebsite();
    }

    /**
     * @Assert\NotBlank(allowNull = true)
     * @Assert\Length(max = 255)
     * @Field
     */
    public function getLogo(): ?string
    {
        return parent::getLogo();
    }

    /**
     * @return User[]
     *
     * @Security("is_granted('NA', this)")
     * @Field
     */
    public function getUsers(): array
    {
        return parent::getUsers();
    }

    /**
     * @return string[]
     */
    public function getProductsPictures(): array
    {
        $products    = $this->getProducts();
        $allPictures = [];

        foreach ($products as $product) {
            $pictures = $product->getPictures();

            if (empty($pictures)) {
                continue;
            }

            $allPictures = array_merge($allPictures, $pictures);
        }

        return $allPictures;
    }
}
