<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\BaseOrder;
use Symfony\Component\Validator\Constraints as Assert;
use TheCodingMachine\GraphQLite\Annotations\Field;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Order class maps the 'orders' table in database.
 *
 * @Type
 */
class Order extends BaseOrder
{
    public function __construct(User $user, Product $product, int $quantity)
    {
        parent::__construct($user, $product, $quantity, $product->getPrice());
    }

    /**
     * @Field
     * @Assert\Positive(message="positive")
     */
    public function getQuantity(): int
    {
        return parent::getQuantity();
    }

    /**
     * @Field
     * @Assert\Positive(message="positive")
     */
    public function getUnitPrice(): float
    {
        return parent::getUnitPrice();
    }

    /**
     * @Field
     * @Assert\Positive(message="positive")
     */
    public function getTotal(): float
    {
        return $this->getUnitPrice() * $this->getQuantity();
    }
}
