<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\BaseRight;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Right class maps the 'rights' table in database.
 *
 * @Type
 */
class Right extends BaseRight
{
}
