<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\BaseUser;
use Symfony\Component\Validator\Constraints as Assert;
use TheCodingMachine\GraphQLite\Annotations\Type;
use function Safe\password_hash;
use const PASSWORD_DEFAULT;

/**
 * The User class maps the 'users' table in database.
 *
 * @Type
 */
class User extends BaseUser
{
    /**
     * @Assert\NotBlank
     * @Assert\Length(max = 255)
     */
    public function getFirstName() : string
    {
        return parent::getFirstName();
    }

    /**
     * @Assert\NotBlank
     * @Assert\Length(max = 255)
     */
    public function getLastName() : string
    {
        return parent::getLastName();
    }

    /**
     * @Assert\NotBlank
     * @Assert\Length(max = 255)
     * @Assert\Email
     */
    public function getEmail() : string
    {
        return parent::getEmail();
    }

    public function setPassword(?string $password) : void
    {
        if ($password === null) {
            parent::setPassword($password);

            return;
        }

        parent::setPassword(password_hash($password, PASSWORD_DEFAULT));
    }

    /**
     * @Assert\Choice(callback={"App\Domain\Enum\LocaleEnum", "values"})
     */
    public function getLocale() : string
    {
        return parent::getLocale();
    }

    /**
     * @Assert\Choice(callback={"App\Domain\Enum\RoleEnum", "values"})
     */
    public function getRole() : string
    {
        return parent::getRole();
    }
}
