query products($search: String, $limit: Int!, $offset: Int!) {
  products(search: $search) {
    items(limit: $limit, offset: $offset) {
      id
      name
      price
      company {
        name
      }
      pictures
    }
    count
  }
}
