<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Dao;

use App\Domain\Dao\Generated\BaseResetPasswordTokenDao;

/**
 * The ResetPasswordTokenDao class will maintain the persistence of ResetPasswordToken class into the reset_password_tokens table.
 */
class ResetPasswordTokenDao extends BaseResetPasswordTokenDao
{
}
